apiVersion: v1
kind: Service
metadata:
  name: file-share
  namespace: file-share
  labels:
    app: file-share
spec:
  type: ClusterIP
  selector:
    app: file-share 
  ports:
  - name: http 
    port: 8000
    protocol: TCP
    targetPort: http 
